### ISSUE TITLE
del_colour fails to remove entries from $self->{-cindex}

### ISSUE THREAD

**Issue by openstrike** [eserte/image-xpm#2]
The del_colour method does not remove entries from $self->{-cindex} when it should. The test script below illustrates this behaviour. The first four tests succeed and show that del_colour does decrement $self->{-ncolours} correctly but the $self->{-cindex} hash still has 2 keys, including the colour "black" which should have been deleted.

```
use strict;
use warnings;

use Test::More tests => 5;
use Image::Xpm;

my $xpm = Image::Xpm->new(-width => 1, -height => 1);
$xpm->add_colours ('black');
is ($xpm->get('-ncolours'), 2, '2 colours after adding black');
is_deeply ([sort keys %{$xpm->get('-cindex')}], ['black', 'white'],
        'Now cindex has white and black');
is ($xpm->del_colour ('black'), 1, 'Black deleted');
is ($xpm->get('-ncolours'), 1, '1 colour after deleting black');
is_deeply ([sort keys %{$xpm->get('-cindex')}], ['white'],
        'Now cindex has just white');
```

I have a fix for this to be submitted as a PR shortly.

This bug was discovered when adding additional tests to improve coverage as part of the [CPAN PR Challenge](http://cpan-prc.org/).

**Comment by eserte** [comment]
Thanks, merged!
